# Generated by Django 4.1.3 on 2022-11-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="truck",
            name="overload",
        ),
        migrations.RemoveField(
            model_name="truckmodel",
            name="side_number",
        ),
        migrations.AddField(
            model_name="truck",
            name="side_number",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="Бортовой номер"
            ),
        ),
        migrations.RemoveField(
            model_name="truck",
            name="truck_model",
        ),
        migrations.AddField(
            model_name="truck",
            name="truck_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.truckmodel",
                verbose_name="Модель самосвала",
            ),
        ),
    ]
