# Generated by Django 4.1.3 on 2022-11-23 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_truck_overload_remove_truckmodel_side_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truck",
            name="truck_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model",
                to="tasks.truckmodel",
                verbose_name="Модель самосвала",
            ),
        ),
    ]
